---


# Primers - uncomment the correct set
# ====================================

# Illumina V3-V4 protocol primers
fwd_primer: "TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTACGGGNGGCWGCAG"
rev_primer: "GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGGACTACHVGGGTATCTAATCC"
fwd_primer_rc: "CTGCWGCCNCCCGTAGGCTGTCTCTTATACACATCTGACGCTGCCGACGA"
rev_primer_rc: "GGATTAGATACCCBDGTAGTCCTGTCTCTTATACACATCTCCGAGCCCACGAGAC"


# # Surette V3 protocol
#fwd_primer: "ATTACCGCGGCTGCTGG"
#rev_primer: "CCTACGGGAGGCAGCAG"
#fwd_primer_rc: "CCAGCAGCCGCGGTAAT"
#rev_primer_rc: "CTGCTGCCTCCCGTAGG"

# Surette V3-V4 protocol
# fwd_primer: "NNNNGGACTACHVGGGTWTCTAAT"
# rev_primer: "CCTACGGGAGGCAGCAG"
# fwd_primer_rc: "ATTAGAWACCCBDGTAGTCCNNNN"
# rev_primer_rc: "CTGCTGCCTCCCGTAGG"

# Harrison lab protocol
#fwd_primer: "CCTACGGGNGGCWGCAG"
#rev_primer: "GACTACHVGGGTATCTAATCC"
#fwd_primer_rc: "CTGCWGCCNCCCGTAGG"
#rev_primer_rc: "GGATTAGATACCCBDGTAGTC"


run_name: "Test" 

# max value for expected error for read filtering. Increase to reduce stringency.
max_expected_error: 1.0

# Truncate all reads at this length
read_length_cutoff: 420 

# number of threads for multi-threaded applications - overriden by -j option to snakemake
num_threads: 20

# Directory where the raw reads are stored
read_directory: "test_data"

# database for dada2::assignTaxonomy
database: "~/databases/assignTaxonomy/rdp_train_set_14.fa.gz"
taxa_type: "rdp"

# for the Surette lab protocol, or any other where the forward 16S primer is on the reverse read
# in order for the taxonomy assignment to work correctly the reads need to be in the same direction
# as the database
revcomp: "FALSE"

# Unique sample descriptors - should be in the file names
samples: ["Sample1", "Sample2", "Sample3", "Sample4"]
